// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZzpSeIQbwAAfpR9qcRaySnF4_QcLdUs',
    appId: '1:1003151957712:web:fe88d53be0afc0e8ec48d5',
    messagingSenderId: '1003151957712',
    projectId: 'jobhunt-mobile',
    authDomain: 'jobhunt-mobile.firebaseapp.com',
    storageBucket: 'jobhunt-mobile.appspot.com',
    measurementId: 'G-D7S1QWFKYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH-X46ldqp2c7sXNr5cJH3x1iCMq8qw-U',
    appId: '1:1003151957712:android:f9fa27c899940e2eec48d5',
    messagingSenderId: '1003151957712',
    projectId: 'jobhunt-mobile',
    storageBucket: 'jobhunt-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASlaGjG3FoZaJQ5YXWn1YAMf8Btfh7Q54',
    appId: '1:1003151957712:ios:04086e81b51d5e56ec48d5',
    messagingSenderId: '1003151957712',
    projectId: 'jobhunt-mobile',
    storageBucket: 'jobhunt-mobile.appspot.com',
    iosBundleId: 'com.example.jobhuntMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASlaGjG3FoZaJQ5YXWn1YAMf8Btfh7Q54',
    appId: '1:1003151957712:ios:b7c8eb8f9f6582a3ec48d5',
    messagingSenderId: '1003151957712',
    projectId: 'jobhunt-mobile',
    storageBucket: 'jobhunt-mobile.appspot.com',
    iosBundleId: 'com.flutter.jobhuntMobile.RunnerTests',
  );
}
